/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package grupo10_tp5;

import javax.swing.JInternalFrame;

/**
 *
 * @author matia
 */
public class DirectorioTelefonico extends javax.swing.JFrame {

    /**
     * Creates new form DirectorioTelefonico
     */
    public DirectorioTelefonico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdEscritorio = new img.ImagenFondo();
        jmbMenu = new javax.swing.JMenuBar();
        jmClientes = new javax.swing.JMenu();
        jmiACliente = new javax.swing.JMenuItem();
        jmiBuscarC = new javax.swing.JMenuItem();
        jmiBorrarC = new javax.swing.JMenuItem();
        jmDirectorio = new javax.swing.JMenu();
        jmiBCCiudad = new javax.swing.JMenuItem();
        jmiBCApellido = new javax.swing.JMenuItem();
        jmCiudades = new javax.swing.JMenu();
        jmiACiudad = new javax.swing.JMenuItem();
        jmSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jdEscritorioLayout = new javax.swing.GroupLayout(jdEscritorio);
        jdEscritorio.setLayout(jdEscritorioLayout);
        jdEscritorioLayout.setHorizontalGroup(
            jdEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 906, Short.MAX_VALUE)
        );
        jdEscritorioLayout.setVerticalGroup(
            jdEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 471, Short.MAX_VALUE)
        );

        jmbMenu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jmClientes.setText("Clientes");

        jmiACliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmiACliente.setText("Agregar cliente");
        jmiACliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAClienteActionPerformed(evt);
            }
        });
        jmClientes.add(jmiACliente);

        jmiBuscarC.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmiBuscarC.setText("Buscar cliente");
        jmiBuscarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiBuscarCActionPerformed(evt);
            }
        });
        jmClientes.add(jmiBuscarC);

        jmiBorrarC.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmiBorrarC.setText("Borrar cliente");
        jmiBorrarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiBorrarCActionPerformed(evt);
            }
        });
        jmClientes.add(jmiBorrarC);

        jmbMenu.add(jmClientes);

        jmDirectorio.setText("Directorio");
        jmDirectorio.setToolTipText("");

        jmiBCCiudad.setText("Buscar cliente por ciudad");
        jmiBCCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiBCCiudadActionPerformed(evt);
            }
        });
        jmDirectorio.add(jmiBCCiudad);

        jmiBCApellido.setText("Buscar ciente por apellido");
        jmiBCApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiBCApellidoActionPerformed(evt);
            }
        });
        jmDirectorio.add(jmiBCApellido);

        jmbMenu.add(jmDirectorio);

        jmCiudades.setText("Ciudades");

        jmiACiudad.setText("Agregar ciudad");
        jmiACiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiACiudadActionPerformed(evt);
            }
        });
        jmCiudades.add(jmiACiudad);

        jmbMenu.add(jmCiudades);

        jmSalir.setText("Salir");
        jmSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmSalirMouseClicked(evt);
            }
        });
        jmbMenu.add(jmSalir);

        setJMenuBar(jmbMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdEscritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdEscritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //Menu item Buscar Cliente por Ciudad: Inicializa el internalFrame y llama al metodo mostrarCentrado() para centrar la ventana
    private void jmiBCCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiBCCiudadActionPerformed
        jdEscritorio.removeAll();
        jdEscritorio.repaint();
        VentanaBCCiudad ventanaBCCiudad = new VentanaBCCiudad();
        mostrarCentrado(ventanaBCCiudad);
        ventanaBCCiudad.setVisible(true);
        jdEscritorio.moveToFront(ventanaBCCiudad);
    }//GEN-LAST:event_jmiBCCiudadActionPerformed
    //Menu item Buscar Cliente por Apellido: Inicializa el internalFrame y llama al metodo mostrarCentrado() para centrar la ventana
    private void jmiBCApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiBCApellidoActionPerformed
        jdEscritorio.removeAll();
        jdEscritorio.repaint();
        VentanaBCApellido ventanaBCApellido = new VentanaBCApellido();
        mostrarCentrado(ventanaBCApellido);
        ventanaBCApellido.setVisible(true);
        jdEscritorio.moveToFront(ventanaBCApellido);
    }//GEN-LAST:event_jmiBCApellidoActionPerformed
    //Menu item Salir: sale del programa.
    private void jmSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmSalirMouseClicked
        this.dispose();
    }//GEN-LAST:event_jmSalirMouseClicked
    //Menu item Agregar Cliente: Inicializa el internalFrame y llama al metodo mostrarCentrado() para centrar la ventana
    private void jmiAClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAClienteActionPerformed
        jdEscritorio.removeAll();
        jdEscritorio.repaint();
        VentanaACliente ventanaACliente = new VentanaACliente();
        mostrarCentrado(ventanaACliente);
        ventanaACliente.setVisible(true);
        jdEscritorio.moveToFront(ventanaACliente);
    }//GEN-LAST:event_jmiAClienteActionPerformed
    //Menu item Buscar Cliente: Inicializa el internalFrame y llama al metodo mostrarCentrado() para centrar la ventana
    private void jmiBuscarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiBuscarCActionPerformed
        jdEscritorio.removeAll();
        jdEscritorio.repaint();
        VentanaBuscarC ventanaBuscarC = new VentanaBuscarC();
        mostrarCentrado(ventanaBuscarC);
        ventanaBuscarC.setVisible(true);
        jdEscritorio.moveToFront(ventanaBuscarC);
    }//GEN-LAST:event_jmiBuscarCActionPerformed
    //Menu item Borrar Cliente: Inicializa el internalFrame y llama al metodo mostrarCentrado() para centrar la ventana
    private void jmiBorrarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiBorrarCActionPerformed
        jdEscritorio.removeAll();
        jdEscritorio.repaint();
        VentanaBorrarC ventanaBorrarC = new VentanaBorrarC();
        mostrarCentrado(ventanaBorrarC);
        ventanaBorrarC.setVisible(true);
        jdEscritorio.moveToFront(ventanaBorrarC);
    }//GEN-LAST:event_jmiBorrarCActionPerformed
    //Menu item Agregar Ciudad: Inicializa el internalFrame y llama al metodo mostrarCentrado() para centrar la ventana
    private void jmiACiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiACiudadActionPerformed
        jdEscritorio.removeAll();
        jdEscritorio.repaint();
        VentanaACiudad ventanaACiudad = new VentanaACiudad();
        mostrarCentrado(ventanaACiudad);
        ventanaACiudad.setVisible(true);
        jdEscritorio.moveToFront(ventanaACiudad);
    }//GEN-LAST:event_jmiACiudadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DirectorioTelefonico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DirectorioTelefonico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DirectorioTelefonico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DirectorioTelefonico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DirectorioTelefonico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jdEscritorio;
    private javax.swing.JMenu jmCiudades;
    private javax.swing.JMenu jmClientes;
    private javax.swing.JMenu jmDirectorio;
    private javax.swing.JMenu jmSalir;
    private javax.swing.JMenuBar jmbMenu;
    private javax.swing.JMenuItem jmiACiudad;
    private javax.swing.JMenuItem jmiACliente;
    private javax.swing.JMenuItem jmiBCApellido;
    private javax.swing.JMenuItem jmiBCCiudad;
    private javax.swing.JMenuItem jmiBorrarC;
    private javax.swing.JMenuItem jmiBuscarC;
    // End of variables declaration//GEN-END:variables

    private void mostrarCentrado(JInternalFrame frame){
        jdEscritorio.add(frame);    //1) Agrega el escritorio
        frame.pack();                     //2) Ajusta el contenido
        
        //3) Calcula el tamaño del Escritorio y del frame
        java.awt.Dimension desk = jdEscritorio.getSize();
        java.awt.Dimension frm = frame.getSize();
        int x = Math.max(0,(desk.width - frm.width) / 2);
        int y = Math.max(0,(desk.height - frm.height) / 2);
        //4)Posiciona en el centro
        frame.setLocation(x,y);
    }
}
